name: Milestone10$(Rev:.r)

resources:
  repositories:
  - repository: forcedi # The name used to reference this repository in the checkout step
    type: github
    endpoint: azlamsalamgit
    name: azlamsalam/force-di

pr:
  branches:
    include:
    - develop
    - master

trigger:
  - feature/*
  - hoftix/*
  - bugfix/*


variables:
- group: Tokens



stages:
- stage: Review
  condition: and( ne(variables['build.Reason'], 'PullRequest'), ne(variables['build.sourceBranch'], 'refs/heads/develop'), ne(variables['build.sourceBranch'], 'refs/heads/master') )
  jobs:
  - template: templates/buildplugins.yml  
    parameters:
      name: 'DeployToReview'
      commitToGit: false
      stageToDeploy: 'review'
      version: 'auto'
      environmentToDeploy: 'review'
      toBuild: true
          
       
- stage: Develop
  condition:  eq(variables['build.Reason'], 'PullRequest')
  jobs:
   - template: templates/buildplugins.yml   
     parameters:
      name: 'DeployToDevelop'
      commitToGit: false
      branchToDeploy: 'develop'
      stageToDeploy: 'dev'
      version: 'dev'
      environmentToDeploy: 'development'
      toBuild: true
      

   - job: WaitPluginToInstallonDevelopment
     displayName: 'Wait for  Plugin To Install on Development'
     dependsOn: DeployToDevelop
     pool: server
     steps:
      - task: Delay@1
        inputs:
         delayForMinutes: '2' 

   - template: templates/prtest.yml   
     parameters:
      name: 'TestPrOnLinux'
      image: 'ubuntu-latest'
      dependOnJob: 'WaitPluginToInstallonDevelopment'
      repositoryToCheckout: 'forcedi'
      directory: 'force-di'
      service_connection: $(devhub_service_connection)

  
   - template: templates/prtest.yml   
     parameters:
      name: 'TestPrOnWindows'
      image: 'vs2017-win2016'
      dependOnJob: 'WaitPluginToInstallonDevelopment'
      repositoryToCheckout: 'forcedi'
      directory: 'force-di'
      service_connection: $(devhub_service_connection)
    
   - job: MergeBranchToDevelop
     displayName: 'Wait for  Plugin To Install on Development'
     dependsOn: 
       - TestPrOnWindows
       - TestPrOnLinux
     pool: server
     steps:
      - task: ManualIntervention@8
        inputs:
          instructions: 'Merge feature/bugfix branch to develop'
          emailRecipients: 'azlam.salam@outlook.com'

- stage: Beta
  dependsOn: Develop
  condition: or(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/heads/hotfix/'))
  jobs:
   - template: templates/buildplugins.yml   #Build Template
     parameters:
      name: 'DeployToBeta'
      commitToGit: false
      branchToDeploy: 'develop'
      stageToDeploy: 'beta'
      version: 'beta'
      environmentToDeploy: 'beta'
      toBuild: true


- stage: Production
  dependsOn: Beta
  condition: or(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/heads/hotfix/'))
  jobs:
   - template: templates/buildplugins.yml   #Build Template
     parameters:
      name: 'DeployToProd'
      commitToGit: false
      branchToDeploy: 'develop'
      stageToDeploy: 'prod'
      version: 'beta'
      environmentToDeploy: 'production'
      toBuild: true
   
   - job: MergeBranchToMaster
     displayName: 'Merge Develop Branch to Master'
     dependsOn: 
       - DeployToProd
     pool: server
     steps:
      - task: ManualIntervention@8
        inputs:
          instructions: 'Merge develop branch to master'
          emailRecipients: 'azlam.salam@outlook.com'

  
  